-- Automatically generated file.
INSERT INTO characters (name, slug, rarity, afflatus, dmg_type, race, version)
VALUES
('Ms. Radio', 'ms-radio', 2, 'Spirit', 'Mental', 'Awakened', 1.0),
('Door', 'door', 2, 'Intellect', 'Reality', 'Arcanist', 1.0),
('The Fool', 'the-fool', 3, 'Star', 'Mental', 'Arcanist', 1.0),
('La Source', 'la-source', 3, 'Plant', 'Mental', 'Arcanist', 1.0),
('aliEn T', 'alien-t', 3, 'Star', 'Reality', 'Beyond', 1.0),
('Leilani', 'leilani', 3, 'Beast', 'Reality', 'Arcanist', 1.0),
('John Titor', 'john-titor', 3, 'Intellect', 'Reality', 'Arcanist', 1.0),
('Twins Sleep', 'twins-sleep', 3, 'Spirit', 'Mental', 'Arcanist', 1.0),
('Bette', 'bette', 3, 'Mineral', 'Reality', 'Arcanist', 1.0),
('Darley Clatter', 'darley-clatter', 3, 'Beast', 'Mental', 'Arcanist', 1.0),
('ONiON', 'onion', 3, 'Mineral', 'Reality', 'Arcanist', 1.0),
('Sputnik', 'sputnik', 3, 'Star', 'Mental', 'Awakened', 1.0),
('Nick Bottom', 'nick-bottom', 4, 'Beast', 'Mental', 'Arcanist', 1.0),
('Eagle', 'eagle', 4, 'Plant', 'Reality', 'Arcanist', 1.0),
('Zima', 'zima', 4, 'Plant', 'Mental', 'Arcanist', 1.0),
('Bunny Bunny', 'bunny-bunny', 4, 'Beast', 'Reality', 'Arcanist', 1.0),
('Pavia', 'pavia', 4, 'Beast', 'Mental', 'Mixed', 1.0),
('Oliver Fog', 'oliver-fog', 4, 'Star', 'Reality', 'Arcanist', 1.0),
('Mondlicht', 'mondlicht', 4, 'Mineral', 'Reality', 'Arcanist', 1.0),
('APPLe', 'apple', 4, 'Star', 'Mental', 'Awakened', 1.0),
('Cristallo', 'cristallo', 4, 'Mineral', 'Reality', 'Arcanist', 1.0),
('TTT', 'ttt', 4, 'Star', 'Mental', 'Arcanist', 1.0),
('Rabies', 'rabies', 4, 'Plant', 'Reality', 'Arcanist', 1.0),
('Ms. Moissan', 'ms-moissan', 4, 'Mineral', 'Reality', 'Arcanist', 1.0),
('Poltergeist', 'poltergeist', 4, 'Spirit', 'Mental', 'Arcanist', 1.0),
('Mesmer Jr.', 'mesmer-jr', 4, 'Intellect', 'Mental', 'Arcanist', 1.0),
('Erick', 'erick', 4, 'Star', 'Reality', 'Arcanist', 1.0),
('X', 'x', 5, 'Intellect', 'Reality', 'Arcanist', 1.0),
('Sweetheart', 'sweetheart', 5, 'Beast', 'Reality', 'Arcanist', 1.0),
('Baby Blue', 'baby-blue', 5, 'Star', 'Mental', 'Arcanist', 1.0),
('Charlie', 'charlie', 5, 'Star', 'Mental', 'Arcanist', 1.0),
('Bkornblume', 'bkornblume', 5, 'Plant', 'Reality', 'Arcanist', 1.0),
('Dikke', 'dikke', 5, 'Beast', 'Mental', 'Arcanist', 1.0),
('Sonetto', 'sonetto', 5, 'Mineral', 'Reality', 'Arcanist', 1.0),
('Balloon Party', 'balloon-party', 5, 'Mineral', 'Reality', 'Arcanist', 1.0),
('Necrologist', 'necrologist', 5, 'Mineral', 'Mental', 'Arcanist', 1.0),
('Satsuki', 'satsuki', 5, 'Plant', 'Mental', 'Mixed', 1.0),
('Matilda', 'matilda', 5, 'Star', 'Mental', 'Arcanist', 1.0),
('Tennant', 'tennant', 5, 'Beast', 'Reality', 'Arcanist', 1.0),
('Click', 'click', 5, 'Spirit', 'Mental', 'Arcanist', 1.0),
('Druvis III', 'druvis-iii', 6, 'Plant', 'Mental', 'Arcanist', 1.0),
('Lilya', 'lilya', 6, 'Star', 'Reality', 'Arcanist', 1.0),
('A Knight', 'a-knight', 6, 'Spirit', 'Reality', 'Arcanist', 1.0),
('Sotheby', 'sotheby', 6, 'Plant', 'Reality', 'Arcanist', 1.0),
('Regulus', 'regulus', 6, 'Star', 'Mental', 'Arcanist', 1.0),
('Centurion', 'centurion', 6, 'Beast', 'Reality', 'Arcanist', 1.0),
('An-an Lee', 'an-an-lee', 6, 'Plant', 'Reality', 'Arcanist', 1.0),
('Medicine Pocket', 'medicine-pocket', 6, 'Beast', 'Mental', 'Arcanist', 1.0),
('Voyager', 'voyager', 6, 'Star', 'Mental', 'Beyond', 1.0),
('Eternity', 'eternity', 6, 'Mineral', 'Reality', 'Arcanist', 1.0),
('Ms. NewBabel', 'ms-newbabel', 6, 'Mineral', 'Reality', 'Arcanist', 1.0),
('Diggers', 'diggers', 5, 'Plant', 'Mental', 'Arcanist', 1.1),
('Melania', 'melania', 6, 'Beast', 'Mental', 'Arcanist', 1.1),
('Pickles', 'pickles', 6, 'Mineral', 'Mental', 'Arcanist', 1.1),
('Blonney', 'blonney', 5, 'Star', 'Reality', 'Arcanist', 1.2),
('Horropedia', 'horropedia', 5, 'Mineral', 'Mental', 'Arcanist', 1.2),
('Jessica', 'jessica', 6, 'Plant', 'Reality', 'Beyond', 1.2),
('Tooth Fairy', 'tooth-fairy', 6, 'Star', 'Mental', 'Arcanist', 1.2),
('Kanjira', 'kanjira', 5, 'Plant', 'Mental', 'Arcanist', 1.3),
('Kaalaa Baunaa', 'kaalaa-baunaa', 6, 'Mineral', 'Mental', 'Arcanist', 1.3),
('Shamane', 'shamane', 6, 'Beast', 'Reality', 'Arcanist', 1.3),
('6', '6', 6, 'Intellect', 'Mental', 'Arcanist', 1.4),
('37', '37', 6, 'Star', 'Mental', 'Arcanist', 1.4),
('Desert Flannel', 'desert-flannel', 5, 'Beast', 'Reality', 'Arcanist', 1.5),
('Ulu', 'ulu', 5, 'Mineral', 'Mental', 'Arcanist', 1.5),
('Ezra Theodore', 'ezra-theodore', 6, 'Star', 'Mental', 'Human', 1.5),
('Spathodea', 'spathodea', 6, 'Beast', 'Reality', 'Arcanist', 1.5),
('Yenisei', 'yenisei', 5, 'Star', 'Mental', 'Arcanist', 1.6),
('Getian', 'getian', 6, 'Beast', 'Reality', 'Arcanist', 1.6),
('Jiu Niangzi', 'jiu-niangzi', 6, 'Mineral', 'Reality', 'Mixed', 1.6),
('Isolde', 'isolde', 6, 'Spirit', 'Reality', 'Arcanist', 1.7),
('Marcus', 'marcus', 6, 'Plant', 'Mental', 'Arcanist', 1.7),
('Avgust', 'avgust', 5, 'Plant', 'Mental', 'Arcanist', 1.8),
('Vila', 'vila', 6, 'Plant', 'Mental', 'Arcanist', 1.8),
('Windsong', 'windsong', 6, 'Star', 'Mental', 'Arcanist', 1.8),
('Lorelei', 'lorelei', 5, 'Star', 'Mental', 'Arcanist', 1.9),
('Kakania', 'kakania', 6, 'Plant', 'Mental', 'Arcanist', 1.9),
('Lucy', 'lucy', 6, 'Intellect', 'Reality', 'Awakened', 1.9),
('Semmelweis', 'semmelweis', 6, 'Mineral', 'Reality', 'Infected', 1.9),
('Pioneer', 'pioneer', 3, 'Spirit', 'Mental', 'Awakened', 2.0),
('J', 'j', 6, 'Beast', 'Reality', 'Mixed', 2.0),
('Mercuria', 'mercuria', 6, 'Spirit', 'Mental', 'Arcanist', 2.0),
('Barbara', 'barbara', 5, 'Spirit', 'Mental', 'Mixed', 2.1),
('Argus', 'argus', 6, 'Plant', 'Reality', 'Arcanist', 2.1),
('Tuesday', 'tuesday', 6, 'Spirit', 'Mental', 'Arcanist', 2.1),
('White Rum', 'white-rum', 4, 'Intellect', 'Reality', 'Awakened', 2.2),
('Mr. Duncan', 'mr-duncan', 5, 'Beast', 'Reality', 'Human', 2.2),
('Anjo Nala', 'anjo-nala', 6, 'Beast', 'Mental', 'Beyond', 2.2),
('Lopera', 'lopera', 6, 'Beast', 'Reality', 'Arcanist', 2.2),
('Brimley', 'brimley', 5, 'Mineral', 'Mental', 'Awakened', 2.3),
('Flutterpage', 'flutterpage', 6, 'Star', 'Reality', 'Mixed', 2.3),
('Willow', 'willow', 6, 'Plant', 'Mental', 'Arcanist', 2.3),
('Barcarola', 'barcarola', 6, 'Star', 'Mental', 'Arcanist', 2.4),
('Fatutu', 'fatutu', 6, 'Mineral', 'Mental', 'Arcanist', 2.4),
('Loggerhead', 'loggerhead', 5, 'Plant', 'Mental', 'Awakened', 2.5),
('Liang Yue', 'liang-yue', 6, 'Star', 'Reality', 'Mixed', 2.5),
('Noire', 'noire', 6, 'Plant', 'Mental', 'Arcanist', 2.5),
('Aleph', 'aleph', 6, 'Intellect', 'Mental', 'Human', 2.6),
('Recoleta', 'recoleta', 6, 'Mineral', 'Reality', 'Arcanist', 2.6),
('Name Day', 'name-day', 5, 'Mineral', 'Mental', 'Arcanist', 2.7),
('Hissabeth', 'hissabeth', 6, 'Plant', 'Mental', 'Arcanist', 2.7),
('Kiperina', 'kiperina', 6, 'Star', 'Mental', 'Arcanist', 2.7),
('Buddy Fairchild', 'buddy-fairchild', 5, 'Plant', 'Reality', 'Arcanist', 2.8),
('Ulrich', 'ulrich', 6, 'Intellect', 'Reality', 'Awakened', 2.8),
('Moldir', 'moldir', 6, 'Beast', 'Reality', 'Mixed', 2.8),
('Nautika', 'nautika', 6, 'Spirit', 'Reality', 'Infected', 2.8),
('Charon', 'charon', 6, 'Spirit', 'Mental', 'Awakened', 3.0),
('Sentinel', 'sentinel', 6, 'Mineral', 'Reality', 'Arcanist', 3.0),
('Alexios', 'alexios', 5, 'Beast', 'Reality', 'Human', 2.75),
('Ezio Auditore', 'ezio-auditore', 6, 'Star', 'Reality', 'Human', 2.75),
('Kassandra', 'kassandra', 6, 'Mineral', 'Reality', 'Human', 2.75),
('Corvus', 'corvus', 6, 'Intellect', 'Mental', 'Arcanist', 3.1),
('Rubuska', 'rubuska', 6, 'Mineral', 'Reality', 'Arcanist', 3.1),
('Beryl', 'beryl', 6, 'Intellect', 'Mental', 'Arcanist', 3.2),
('Brume', 'brume', 6, 'Beast', 'Mental', 'Arcanist', 3.2),
('Igor', 'igor', 6, 'Beast', 'Reality', 'Mixed', 3.3),
('Marsha', 'marsha', 6, 'Beast', 'Reality', 'Arcanist', 3.3),
('Reed', 'reed', 4, 'Plant', 'Mental', 'Arcanist', 3.4),
('Cheng Heguang', 'cheng-heguang', 6, 'Star', 'Reality', 'Arcanist', 3.4),
('Paper Heron', 'paper-heron', 6, 'Plant', 'Reality', 'Arcanist', 3.4),
('Lorentz Butterfly', 'lorentz-butterfly', 6, 'Intellect', 'Mental', 'Arcanist', 3.5),
('Ramona', 'ramona', 6, 'Plant', 'Mental', 'Arcanist', 3.5),
('Enigma', 'enigma', 6, 'Intellect', 'Reality', 'Human', 3.6),
('Lady by the Lake', 'lady-by-the-lake', 4, 'Plant', 'Mental', 'Awakened', 3.7),
('Silverwing Eagle', 'silverwing-eagle', 5, 'Plant', 'Reality', 'Arcanist', 3.7),
('Coppélia', 'coppelia', 6, 'Mineral', 'Reality', 'Arcanist', 3.7),
('Rhiannon', 'rhiannon', 6, 'Beast', 'Mental', 'Arcanist', 3.7),
('Ms. Stranger', 'ms-stranger', 6, 'Mineral', 'Mental', 'Arcanist', 3.7)

ON CONFLICT (slug) DO NOTHING;
